# ??????
scm:
  name: Scm
  version: 4.8.0
  copyrightYear: 2025
  demoEnabled: true
  profile: D:/scm/uploadPath
  addressEnabled: false
  sql:
    init:
      enabled: true
      location: classpath:sql/mysql/
      fail-on-error: false

# ??????
server:
  # ????HTTP??
  port: 8088
  servlet:
    # ??????
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# ????
logging:
  level:
    com.scm: debug
    org.springframework: warn

# ????
user:
  password:
    maxRetryCount: 5

# Spring??
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true

# MyBatis
mybatis:
  typeAliasesPackage: com.scm.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: false
    captchaType: math
  cookie:
    domain:
    path: /
    httpOnly: true
    maxAge: 30
    cipherKey:
  session:
    # ??????-1 ??????
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 10
    maxSession: -1
    kickoutAfter: false
  rememberMe:
    enabled: true

# XSS??
xss:
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*

# CSRF??
csrf:
  enabled: false
  whites: /druid

# Swagger??
swagger:
  enabled: true
