-- 修复「客户管理」已占用 2800–2802 导致 SCM「数据权限」INSERT IGNORE 静默失败的问题。
-- 本补丁使用 2850–2854 段；与 menu.sql 中对应 INSERT 一致。
-- 执行后请继续执行 menu.sql 中「SCM 菜单维度」UPDATE 段（约从 CALL add_table_column('sys_menu', 'menu_biz_category'...) 起），
-- 至少确保：UPDATE ... WHERE perms LIKE 'scmAuth:%' 已对新行写入 auth_type 等字段。

INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('2850', '数据权限', '0', '13', '#', '', 'M', '0', '1', '', 'fa fa-shield', 'admin', sysdate(), '', null, 'SCM医院/供应商菜单与数据权限', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('2851', '医院菜单授权', '2850', '1', '/scm/auth/hospitalMenu', '', 'C', '0', '1', 'scmAuth:hospitalMenu:view', 'fa fa-hospital-o', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28511', '医院菜单查询', '2851', '1', '#', '', 'F', '0', '1', 'scmAuth:hospitalMenu:query', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28512', '医院菜单保存', '2851', '2', '#', '', 'F', '0', '1', 'scmAuth:hospitalMenu:edit', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28513', '医院菜单重置', '2851', '3', '#', '', 'F', '0', '1', 'scmAuth:hospitalMenu:reset', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('2852', '供应商菜单授权', '2850', '2', '/scm/auth/supplierMenu', '', 'C', '0', '1', 'scmAuth:supplierMenu:view', 'fa fa-truck', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28521', '供应商菜单查询', '2852', '1', '#', '', 'F', '0', '1', 'scmAuth:supplierMenu:query', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28522', '供应商菜单保存', '2852', '2', '#', '', 'F', '0', '1', 'scmAuth:supplierMenu:edit', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28523', '供应商菜单重置', '2852', '3', '#', '', 'F', '0', '1', 'scmAuth:supplierMenu:reset', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('2853', '医院供应商数据权限', '2850', '3', '/scm/auth/hospitalSupplierPerm', '', 'C', '0', '1', 'scmAuth:hospitalSupplier:view', 'fa fa-ban', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28531', '黑名单列表', '2853', '1', '#', '', 'F', '0', '1', 'scmAuth:hospitalSupplier:list', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28532', '黑名单维护', '2853', '2', '#', '', 'F', '0', '1', 'scmAuth:hospitalSupplier:add', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28533', '黑名单删除', '2853', '3', '#', '', 'F', '0', '1', 'scmAuth:hospitalSupplier:remove', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('2854', '医院供应商菜单授权', '2850', '4', '/scm/auth/hospitalSupplierMenu', '', 'C', '0', '1', 'scmAuth:hospitalSupplierMenu:view', 'fa fa-sitemap', 'admin', sysdate(), '', null, '医院向名下供应商授予联合菜单权限', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28541', '医院供应商菜单查询', '2854', '1', '#', '', 'F', '0', '1', 'scmAuth:hospitalSupplierMenu:query', '#', 'admin', sysdate(), '', null, '', '0');
INSERT IGNORE INTO sys_menu (menu_id, menu_name, parent_id, order_num, url, target, menu_type, visible, is_refresh, perms, icon, create_by, create_time, update_by, update_time, remark, status) VALUES('28542', '医院供应商菜单保存', '2854', '2', '#', '', 'F', '0', '1', 'scmAuth:hospitalSupplierMenu:edit', '#', 'admin', sysdate(), '', null, '', '0');

-- 若库中尚未有 menu_biz_category 等列，须先执行 column.sql / menu.sql 中的 add_table_column 段。
UPDATE sys_menu SET auth_type = 'platform', hospital_grant_supplier_flag = '0', default_open_scope = 'none', menu_biz_category = 'scm_auth'
WHERE del_flag = '0' AND (perms LIKE 'scmAuth:%' OR perms LIKE 'system:%');
UPDATE sys_menu SET auth_type = 'hospital', hospital_grant_supplier_flag = '0', default_open_scope = 'all_hospital', menu_biz_category = 'scm_auth'
WHERE del_flag = '0' AND perms LIKE 'scmAuth:hospitalSupplierMenu%';
